### ISSUE TITLE
Label_2 label's working issue 

### ISSUE THREAD

**Issue by Karansemwal** [Arsenic-ATG/Qt-calculator#27]
Hey @Arsenic-ATG  , I just cloned and run the calculator application label_2 object's text doesn't gets updated after using the operations buttons ( +, -, *, % )

**Comment by Arsenic-ATG** [comment]
@Karansemwal thanks for opening issue 

Currently `label_2` is only updated as soon as the equal(`=`) button is pushed ( see `MainWindow::on_pushButton_equals_released()` in mainwindow.cpp )

https://github.com/Arsenic-ATG/Qt-calculator/blob/f98b92bd02c7053a718e433999db8f66e5b81c56/Calculator/mainwindow.cpp#L161


Though this is happening by design, It certainly is not the best behaviour as the user currently have no way to see the current operation that is taking place.

**Comment by Karansemwal** [comment]
Yes @Arsenic-ATG , I navigated through the codebase , maybe if we try this it will be resolved , Keeping the label_1's text initially 0 and change it like this : Whenever this function is called **binary_operation_pressed()** which is whenever any operators like +, -, * , %  buttons are pressed change the label_1's text **ui->label_2->setText(ui->label->text() + " + ");** . I am just learning Qt so it might take time , you can assign this to me so that i can try out :)
