### ISSUE TITLE
it seems that the newest code lost the head file <math.h>

### ISSUE THREAD

**Issue by mhw-Parker** [Arsenic-ATG/Qt-calculator#43]
**Describe the bug**
[A clear and concise description of what the bug is.](error: 'log10' was not declared in this scope)

**Comment by yashwantpradhan** [comment]
I want to work on this issue. Please assign me this issue.

**Comment by H4CK3R01P** [comment]
I can fix this issue.

**Comment by Arsenic-ATG** [comment]
Thanks for pointing this out

This is because you might be trying to build the program from command line.

Qtcreator uses [it's own environment](https://doc.qt.io/qtcreator/creator-how-set-project-environment.html) when building/running the project where it links a bunch of liberties to it hence the project is building successfully when running with qt creator and not with command line 

I might work on getting this project rid of qtcreator as a dependency altogether.
